# Generated by Django 4.2 on 2023-04-29 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductModifications',
        ),
    ]
