# Generated by Django 4.2.1 on 2023-09-10 10:21

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_delete_productmodifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=shop.models.UUIDFileStorage(), upload_to='images/', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='itemnumber',
            name='on_sale',
            field=models.BooleanField(default=False, verbose_name='В продаже'),
        ),
        migrations.AlterField(
            model_name='productphotos',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=shop.models.UUIDFileStorage(), upload_to='images/', verbose_name='Фото товара'),
        ),
    ]
