# Generated by Django 4.1.4 on 2023-09-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_image_alter_itemnumber_on_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemnumber',
            name='size',
            field=models.CharField(max_length=128, verbose_name='Размер товара данного артикула'),
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Размер товара'),
        ),
    ]
